### ISSUE TITLE
Troubleshooting my Node.js issues on TypeBot project.

### ISSUE THREAD

**Issue by kongxingagit** [rwaldron/javascript-robotics#20]
Hello, 

I cannot seem to successfully execute the align.js program using node on my Arduino Uno. This is in reference to chapter 2 (Typebot). The error I am seeing on entering the the command in terminal:

          node align.js  

is

"Device or Firmware Error A timeout occurred while connecting to the Board. Please check that you've properly flashed the board with the correct firmware. See: https://github.com/rwaldron/johnny-five/wiki/Getting-Started#trouble-shooting".

Prior to this I receive what appears to be detailed listing of the devices connected to serial ports on my machine.
                        "1434196340540 Device(s) COM1, COM3, COM6
                          1434196340659 Connected COM1"

![image](https://cloud.githubusercontent.com/assets/11729011/8144468/24288cda-11ae-11e5-96f8-2d9a329d8155.png)

To me this appears bad, as my Arduino Uno is on COM6, per windows Device manager (I know, I should use linux, but bear with me please).

To troubleshoot, I went and repeated the steps in the Appendix on installing Johnny-Five. I created a blink.js program that should blink the LED 13, ran 

                     node blink.js
and received the same error message as above. There was no blinking at all of course.

To me this seems to signify that the failure point is somewhere on how I am using node to communicate with my Uno, and nothing to do with the details of align.js.

Here is a list of the steps I have took in order to troubleshoot.

1. Plugged in Uno to computer using USB cable.
2. See auto driver install failed, manually downloaded and installed Arduino IDE.
3. Open Arduino IDE, set Tools/board to Arduino Uno, set Tools/Port to COM 6 (Arduino Uno).
4. File/examples/basics/blink.
5. Hit upload.
6. See the Led blinking orange. So seems the Arduino is working.
6a. File/examples/firmata/StandardFirmata.
6b. Upload, appears to have completed without issues.
7. I have node already installed, so mkdir TypeBot for a typebot directory.
8. cd Typebot.
9. npm install johnny-five.
10. Checked Typebot directory, see new folder node_modules/johnny-five so I believe we have johnny-five installed properly.
11. In the Typebot directory, create align.js and blink.js.
12. node align.js-->Results in error message from top of post.
13. node blink.js-->Same error message.
14. Go to link in error message, retry firmata install.
15. npm install johnny-five --msvs_version=2012 (can someone explain what is happening here?)
16. Retry node align.js, same error.

![image](https://cloud.githubusercontent.com/assets/11729011/8144474/49a5f5d8-11ae-11e5-8236-446907450bfd.png)

What should I do in order to troubleshoot this issue, which I think is the fact that only COM1 port is connected even though I think I need COM6 to be connected as well? I have a spare Beaglebone black, can someone suggest a way I can use that to troubleshoot this issue?

**Comment by rwaldron** [comment]
cc @bryan-m-hughes

**Comment by kongxingagit** [comment]
Hi Rick

Thanks for the CC to Bryan, but I think we can probably chalk this to user idiocy and the ever present need to RTFM. I have made slightly more progress since then after diving into the johnny-five documentation.

What we have is calling Board without parameters for port defaults to "detected". Running either blink.js, or align.js without parameters would result in 3 COM ports detected, but will connect to COM1 instead of COM6 where the Arduino is on. Maybe it defaults to the first of many detected, or COM1 looks like an Arduino.

Well the stupid solution was to plug my arduino into COM1. I know COM3 was my printer, COM1 was marked as "Communication port" and I was not sure what that was.

 From documentation, "when connecting to a USB serial device, such as an Arduino, you do not need to specify the device path or COM port, Johnny-Five will determine which to connect to and connect automatically." I thought, what the heck, let's specify COM6 and see what happens even though it does not seem you need to. Hence changing blink.js (The hello world of node robotics, blinks and LED).

var five = require("johnny-five");
var board = new five.Board({port: "COM6"});

board.on("ready", function () {
	var led=new five.Led(13);
    led.blink();
});

then running 

                     node blink.js
![image](https://cloud.githubusercontent.com/assets/11729011/8149302/c2602ece-128c-11e5-9c46-d43a777d93de.png)




results in my UNO blinking like a Christmas tree. Success! Now to try this on align.js with the addition of the port parameter.

I will have to make required changes to the other sample programs, but I think I can proceed on this project. Probably finish it up before the weekend is up. Hat tip to https://github.com/ychou85 for the suggested fix.

I am still unsure why COM1 is being connected to instead of COM6 when COM6 is the arduino uno even though it looks to me node should be correctly detecting and connecting to the arduino without the need to specify, but explicitly specifying the port appears to be the way to go. Probably something to do with my specific set up (tons of peripherals, windows).

**Comment by nebrius** [comment]
Glad you got it at least temporarily working @kongxingagit :) (sorry for not getting back sooner, I was at NodeConf with limited internet and no cell signal for the last four days)

Specifying the port manually the way you did is the approach I would take. With the most recent issue, perhaps it changed from COM6 to something else?

Can you do me another favor and install node-serialport directly and follow the steps under [List Ports](https://github.com/voodootikigod/node-serialport#list-ports) with your Arduino plugged in? I'm guessing something with that is throwing off the automatic detection.

**Comment by kongxingagit** [comment]
Hi Bryan @nebrius ,
First off, let me say that your type bot design is very cool :+1:  and the chapter instructions are well written, which is why it is my first project from the book. Unfortunately that means I am climbing the learning curve in both johnny-five, node, and Arduino hacking.

I am going to try out your suggestion tomorrow or asap. I was documenting the possible 2nd issue that appears related to COM6. 

My typebot.js and servocontrol.js files were downloaded from this repo, and I made the small change of specifying COM6 at the end of typebot.js so it appears as thus : 
 
```
var board = new five.Board({port: "COM6"});
board.on('ready', function() {
  servocontrol.init(board, SERVO_CONFIG, run);
});
```

Before that I had plugged each joint servo back into pin 3 on the UNO and run align.js to get the arm back into the resting position.

Ok, running typebot.js

```
D:\gitprojects\Typebot> node typebot,js
1434498729973 Connected COM6
1434498733255 Repl Initialized
>> The 'isInverted' property has been renamed 'invert'
Typing key h
Typing key e
Typing key l
Typing key l
Typing key o
Typing key w
Typing key o
Typing key r
Typing key l
Typing key d
D:\gitprojects\Typebot> node typebot,js
1434498760624 Connected COM6
undefined
undefined
undefined
1434498770621 Device or Firmware Error A timeout occurred while connecting to th
e Board.

Please check that you've properly flashed the board with the correct firmware.
See: https://github.com/rwaldron/johnny-five/wiki/Getting-Started#trouble-shooti
ng

Error: A timeout occurred while connecting to the Board.
    at Board.<anonymous> (D:\gitprojects\Typebot\node_modules\johnny-five\lib\bo
ard.js:411:26)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
D:\gitprojects\Typebot>
```

So the first run of typebot.js was somewhat promising. The arm contorted into some position (see pic) once "Typing key h" appeared, so the Uno seems to be getting and responding to some signal. When I ran typebot.js again, then we get "undefined" X3 and pretty much the same timeout error as before. However from the log it appears that COM6 was connected. 
![typebot3 1](https://cloud.githubusercontent.com/assets/11729011/8197336/d5352764-1464-11e5-8c15-99a248a58591.jpg)


I checked the Arduino IDE and COM6 had vanished in the Tools menu as well. At this point to get COM6 back I had to unplug and replug my USB cable of the Arduino.

Should this be happening if I run typebot.js twice in a row? I am thinking of trying to Ctr+c before the second run.

I will be trying the steps under list ports and reporting on it soon.

**Comment by nebrius** [comment]
@kongxingagit Thanks, I'm glad you liked the chapter!

Here's a thought. Can you try running without any jumpers connected to the Arduino? It's possible that the servos are drawing too much power from the Arduino, and this should tell us one way or another. If it runs fine, then we need another power source, otherwise it's a different problem.

If the servos are drawing too much power, you can get an external battery pack with 4 AA batteries to power the servos. The basic setup will be similar to the diagram shown at https://github.com/nebrius/jsfest-sf-2014-nodebot.

**Comment by kongxingagit** [comment]
Ok, so installing serialport and listing the ports seems to detect COM1 and COM6 when I have the Arduino plugged in.
```
D:\gitprojects\typebot> npm install serialport
-
> serialport@1.7.4 install D:\gitprojects\typebot\node_modules\serialport
> node-pre-gyp install --fallback-to-build

[serialport] Success: "D:\gitprojects\typebot\node_modules\serialport\build\ser
alport\v1.7.4\Release\node-v11-win32-x64\serialport.node" is installed via remo
e
serialport@1.7.4 node_modules\serialport
├── async@0.9.0
├── bindings@1.2.1
├── sf@0.1.7
├── nan@1.8.4
├── debug@2.2.0 (ms@0.7.1)
└── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
D:\gitprojects\typebot> node listports.js
COM1
ACPI\PNP0501\1
(Standard port types)
D:\gitprojects\typebot> node listports.js
COM1
ACPI\PNP0501\1
(Standard port types)
COM6
USB\VID_2341&PID_0043\7543932393535131E050
Arduino LLC (www.arduino.cc)
D:\gitprojects\typebot>
```

As for your point in power supply, d'oh! I had done a mini beaglebone black project and I had used an external power source for 1 servo, now I am trying to run 3 servos off an arduino attached only to a USB. Being that I only had 1 of those, I am ordering a few more, and waiting for them to ship, so it will be a while until I update to that point.

**Comment by nebrius** [comment]
You may still have problems even if you use multiple Arduinos. The limiting factor with servos is typically the mount of power that the computer puts out over USB, not the Arduino itself. Can you try powering them using AA batteries, instead of the Arduino?

**Comment by kongxingagit** [comment]
Sorry for the confusion. I am ordering a couple of battery holders, as well as some DC barrel jack-female adaptors to go with my wall adaptor power supply, not additional Arduinos (although those would be nice too). In this case I can either use battery or a wall plug + adaptor + resistors setup. 

I am pretty sure I need the external power, because I recall that the board (at least the Beaglebone which I used before) can barely run 1 servo, let alone 3. Align.js ran fine as it was 1 servo, but I am not getting away with three.

**Comment by nebrius** [comment]
Oh sorry, my mistake :) Let us know how things work out!

**Comment by kongxingagit** [comment]
Great success! I connected a 5V DC Wall Adapter power Supply to a DC Barrel Jack Adaptor, hooked that up to the breadboard, then a jumper wire from the GND pin on the Arduino to the ground section on bread board, then ran typebot.js. I even got this youtube video to show for it!

https://www.youtube.com/watch?v=7xWRiH4sty0&feature=youtu.be

Once more, thank you Bryan @nebrius for your help. I am going to try to take this concept further through your extra challenge suggestions, such as the OCR self calibrating bot, or the one I prefer, the voice recognizing typing secretary bot (words per minute=5). I actually have an idea involving my electric piano. This is great fun, hard fun, but great.

**Comment by nebrius** [comment]
\o/ That's fantastic @kongxingagit! I'm glad you got it working! If you get any videos of your other ideas, I would love to see them posted on Twitter (I'll retweet them so hard, I'm @nebrius there too).
